### ISSUE TITLE
organization page needs updated and linked from the menu

### ISSUE THREAD

**Issue by nspilman** [junior-dev-struggle-bus/juniordevstrugglebus#16]
https://juniordevstrugglebus.com/organization

The About write up should be rewritten. 
The positions need to be updated.
The page should be added to the menu bar.

**Comment by bhurstGH** [comment]
Saw it in there when I was cleaning stuff up last night. Maybe I'll at least get it linked next time I'm poking around in there.

**Comment by jlbaldwin** [comment]
I can update the menu bar. Do the About write up and positions still need to be updated?

**Comment by AvianAnalyst** [comment]
Bump. 

And also it looks like the positions and writeup are hard coded in. I haven't super familiarized myself with the setup yet, but would it be better to setup a data store so things like the positions can be changed inside an admin portal? If I missed something, my bad!

**Comment by bhurstGH** [comment]
@AvianAnalyst Definitely something to consider, though at least the positions themselves SHOULDN'T have to be changed to often, hehe. Something we could setup for sure, though.

**Comment by nspilman** [comment]
Yeah - I think this is a definite should, but should be in a separate issue.

**Comment by AvianAnalyst** [comment]
Is this part of what #30 was opened in response to? Or should I draft a new issue @nspilman 

@bhurstGH oh certainly! More just like, if other positions get added (such as staff/admins) and the team grows, it sounds tedious to make pull requests for each change.

**Comment by nspilman** [comment]
Updated, ready to close. We should soon explore maintaining the org information outside of the html itself.
