### ISSUE TITLE
changing the website's resources API call to call one of our netlify functions 

### ISSUE THREAD

**Issue by nspilman** [junior-dev-struggle-bus/juniordevstrugglebus#21]
Currently the website asks an API endpoint on Nate Spilman's personal django server ask for the resources data. We'll build the resource get call in Node via a Netlify function and then move the api end point on the resources page to the netlify function.

**Comment by nspilman** [comment]
Closing issue for larger overall "we need a data store" issue.

**Comment by AvianAnalyst** [comment]
Just for ease/cross referencing that's #30 (I believe)
