### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by Xoadra** [junior-dev-struggle-bus/juniordevstrugglebus#28]
I noticed that the [blog's repo](https://github.com/junior-dev-struggle-bus/junior-dev-struggle-blog) has a license but this one does not.  As a community that encourages open source contributions, I would recommend adding a license to this project as well.

**Comment by nspilman** [comment]
I dig. MIT? https://opensource.org/licenses/MIT

**Comment by Xoadra** [comment]
Whatever you feel best complements the goals of the community.  It may be a good thing to discuss at Monday's meetup.

**Comment by nspilman** [comment]
Added MIT license. Can discuss revision to a different open source license based on our needs in the future
