### ISSUE TITLE
List children on Organization page are not provided keys

### ISSUE THREAD

**Issue by Xoadra** [junior-dev-struggle-bus/juniordevstrugglebus#35]
While working on PR #34, I visited the Organization page and found the below error in my console:

![Screen Shot 2019-10-22 at 12 55 48 AM](https://user-images.githubusercontent.com/26556825/67267247-bf030b00-f466-11e9-8e8d-1dddd46e241b.png)

I checked the code and noticed that the lists of people for the board of directors and the executive team aren't providing keys to the `<Position />` components that are being generated.

React recommends using immutable and distinct keys for list items but also cautions against simply incrementing a number to represent a key for each list item.  Because there is identical information shared between list items, the solution to this complicates things a little.

That said, using an incremented number as a key for these may not be that big of a deal here, but I thought it would be worth mentioning at the very least.  You could also just extend the map function and use the array's index argument for each list item instead.

**Comment by Xoadra** [comment]
I found another occurrence of this issue on the Resource page where resource objects are being mapped to individual `<Resource />` components.

Here I would recommend using the links on the resource objects as the keys for these components since they should be unique (even though we don't enforce it yet) so as to not list a resource that's already been added.

**Comment by hoangviet1993** [comment]
@Xoadra may I be assigned this issue?

Since `execList` and `bodList` are constant, I think we are safe to use the map's indexes as keys here.

**Comment by Xoadra** [comment]
Go for it!

I'm not sure what the status of resources is so you'll have to ask @nspilman about that.  He and I were working on moving stored resources from a Google spreadsheet over to FaunaDB but I don't know the status of that currently.
